<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'lockSSL' => true,
        'loginSecurityLevel' => 'normal',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'driver' => 'mysqli',
                'persistentConnection' => true,
            ],
        ],
    ],
    'EXT' => [
        'extConf' => [
            'aimeos' => 'a:11:{s:8:"siteCode";s:7:"default";s:7:"siteTpl";s:7:"default";s:9:"autoSetup";s:1:"1";s:7:"cleanDb";s:1:"1";s:11:"useDemoData";s:0:"";s:20:"useRealUrlAutoConfig";s:1:"1";s:9:"cacheName";s:5:"Typo3";s:6:"useAPC";s:1:"1";s:9:"apcPrefix";s:3:"t3:";s:12:"showPageTree";s:1:"0";s:17:"realUrlAddNoCache";s:1:"1";}',
            'aimeos_dist' => 'a:0:{}',
            'aimeos_dist7' => 'a:0:{}',
            'aimeos_pay' => 'a:0:{}',
            'bootstrap_package' => 'a:11:{s:16:"disablePageTsRTE";s:1:"0";s:27:"disablePageTsBackendLayouts";s:1:"0";s:20:"disablePageTsTCEMAIN";s:1:"0";s:20:"disablePageTsTCEFORM";s:1:"0";s:30:"disablePageTsTtContentPreviews";s:1:"0";s:36:"disablePageTsNewContentElementWizard";s:1:"0";s:21:"disableLessProcessing";s:1:"0";s:21:"disablePageTsAdmPanel";s:1:"0";s:4:"Logo";s:84:"../typo3conf/ext/bootstrap_package/Resources/Public/Images/Backend/TopBarLogo@2x.png";s:18:"disableBackendSkin";s:1:"0";s:9:"LoginLogo";s:83:"../typo3conf/ext/bootstrap_package/Resources/Public/Images/Backend/LoginLogo-v7.png";}',
            'cs_seo' => 'a:11:{s:17:"enablePathSegment";s:1:"1";s:15:"realURLAutoConf";s:1:"1";s:11:"tsConfigPid";s:1:"1";s:8:"maxTitle";s:2:"57";s:14:"maxDescription";s:3:"156";s:11:"maxNavTitle";s:2:"50";s:12:"inPageModule";s:1:"0";s:10:"evaluators";s:38:"Title,Description,H1,H2,Images,Keyword";s:8:"minTitle";s:2:"40";s:14:"minDescription";s:3:"140";s:5:"maxH2";s:1:"6";}',
            'easy_googlemap' => 'a:0:{}',
            'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
            'filemetadata' => 'a:0:{}',
            'gsai_email' => 'a:0:{}',
            'gsaimeos' => 'a:0:{}',
            'gsaimeos_dist7' => 'a:0:{}',
            'gsaimeos_theme' => 'a:0:{}',
            'gsaimeos_zf' => 'a:0:{}',
            'gsaimeosthemesauto' => 'a:0:{}',
            'gscacheconfig' => 'a:3:{s:19:"cachingConfigEnable";s:1:"1";s:25:"cachingOptimizationEnable";s:1:"1";s:31:"cachingCliFallbackExtbaseObject";s:1:"1";}',
            'gsfavicon' => 'a:0:{}',
            'gslib' => 'a:0:{}',
            'gswarranty' => 'a:0:{}',
            'introductionplus' => 'a:0:{}',
            'lowlevel' => 'a:0:{}',
            'metaseo' => 'a:4:{s:10:"pagingSize";s:0:"";s:10:"enableBeta";s:0:"";s:23:"enableIntegrationTTNews";s:1:"1";s:29:"sitemap_clearCachePossibility";s:0:"";}',
            'opendocs' => 'a:0:{}',
            'pagehits' => 'a:0:{}',
            'realurl' => 'a:8:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:17:"segTitleFieldList";s:0:"";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";s:17:"enableBadBehavior";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'reports' => 'a:0:{}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'static_info_tables' => 'a:1:{s:13:"enableManager";s:1:"0";}',
            'sys_action' => 'a:0:{}',
            'taskcenter' => 'a:0:{}',
            'typoscript_rendering' => 'a:0:{}',
            'zf2018' => 'a:0:{}',
        ],
    ],
    'EXTCONF' => [
        'helhum-typo3-console' => [
            'initialUpgradeDone' => '8.7',
        ],
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'FE' => [
        'debug' => false,
        'loginSecurityLevel' => 'normal',
        'pageNotFound_handling' => 'REDIRECT:/404',
        'pageNotFound_handling_statheader' => '',
        'pageUnavailable_force' => false,
        'pageUnavailable_handling' => 'REDIRECT:/unavailable.html',
    ],
    'GFX' => [
        'jpg_quality' => '80',
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'RGB',
        'processor_effects' => -1,
        'processor_enabled' => true,
        'processor_path' => '/usr/bin/',
        'processor_path_lzw' => '/usr/bin/',
    ],
    'INSTALL' => [
        'wizardDone' => [
            'TYPO3\CMS\Install\Updates\AccessRightParametersUpdate' => 1,
            'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\Compatibility6ExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ContentTypesToTextMediaUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FileListIsStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FilesReplacePermissionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\LanguageIsoCodeUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MediaceExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MigrateMediaToAssetsForTextMediaCe' => 1,
            'TYPO3\CMS\Install\Updates\MigrateShortcutUrlsAgainUpdate' => 1,
            'TYPO3\CMS\Install\Updates\OpenidExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\PageShortcutParentUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ProcessedFileChecksumUpdate' => 1,
            'TYPO3\CMS\Install\Updates\TableFlexFormToTtContentFieldsUpdate' => 1,
            'TYPO3\CMS\Install\Updates\WorkspacesNotificationSettingsUpdate' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\DeprecatedRteProperties' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\RteAcronymButtonRenamedToAbbreviation' => 1,
        ],
    ],
    'MAIL' => [
        'defaultMailFromAddress' => 'webmaster@zwergenfabrik.ch',
        'defaultMailFromName' => 'Zwergenfabrik GmbH',
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i -f webmaster@zwergenfabrik.ch',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'UTF8filesystem' => '1',
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\ApcuBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'devIPmask' => '',
        'displayErrors' => 0,
        'enableDeprecationLog' => false,
        'encryptionKey' => 'encryptionKey',
        'exceptionalErrors' => 20480,
        'fileCreateMask' => '0660',
        'folderCreateMask' => '2770',
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'phpTimeZone' => 'Europe/Zurich',
        'sitename' => 'Zwergenfabrik',
        'sqlDebug' => 0,
        'systemLocale' => 'de_CH.utf8',
        'systemLogLevel' => 2,
        'trustedHostsPattern' => 'trustedHostsPattern',
    ],
];
